[[headers]]
  for = "/*.(js|mjs)"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

[build]
  command = "npm run build"
  publish = "dist"
  
[build.environment]
  # Use production API URL
  VITE_API_URL = "https://africa-risk-api.onrender.com"

# Handle API requests during local Netlify development
[[redirects]]
  from = "/api/*"
  to = "https://africa-risk-api.onrender.com/:splat"
  status = 200
  force = true

# SPA redirect for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200