version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8080

  backend:
    build: 
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    environment:
      - DEBUG=True
      - ALLOW_ORIGIN=http://localhost:3000

volumes:
  backend_data:
