version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:80"  # Map container's port 80 to host's port 3000
    environment:
      - VITE_API_URL=http://localhost:8081  # Match backend port
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8080"  # Map container's port 8080 to host's port 8081
    environment:
      - DEBUG=False
      - ALLOW_ORIGIN=http://localhost:3000  # Match frontend port
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  backend_data:
