version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "5173:4173"
    restart: always
